CREATE TABLE IF NOT EXISTS authorized_users (
  id INT AUTO_INCREMENT PRIMARY KEY, phone_number VARCHAR(32) NOT NULL UNIQUE,
  full_name VARCHAR(150) NOT NULL, company VARCHAR(200), is_active BOOLEAN NOT NULL DEFAULT TRUE,
  search_limit INT NOT NULL DEFAULT 100, ine_ocr_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  total_queries INT NOT NULL DEFAULT 0, last_access DATETIME(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS blocked_attempts (
  id BIGINT AUTO_INCREMENT PRIMARY KEY, phone_number VARCHAR(32) NOT NULL,
  message_content TEXT, attempt_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX blocked_recent (phone_number, attempt_time)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_jobs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY, message_sid VARCHAR(64) NOT NULL UNIQUE,
  phone VARCHAR(32) NOT NULL, payload LONGBLOB NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending', attempts INT NOT NULL DEFAULT 0,
  available_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), last_error VARCHAR(200),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX job_ready (status, available_at, id), INDEX job_phone (phone, id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_conversations (
  phone VARCHAR(32) PRIMARY KEY, data LONGBLOB NOT NULL, expires_at DATETIME(3) NOT NULL,
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_searches (
  id CHAR(36) PRIMARY KEY, message_sid VARCHAR(64) NOT NULL UNIQUE, phone VARCHAR(32) NOT NULL,
  quota_day CHAR(10) NOT NULL, status VARCHAR(20) NOT NULL, query LONGBLOB NOT NULL,
  result LONGBLOB, summary LONGBLOB, error_code VARCHAR(80),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), completed_at DATETIME(3),
  INDEX search_quota (phone, quota_day, status), INDEX search_history (phone, completed_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_reports (
  id CHAR(36) PRIMARY KEY, message_sid VARCHAR(64) NOT NULL UNIQUE, phone VARCHAR(32) NOT NULL,
  filename VARCHAR(100) NOT NULL, expires_at DATETIME(3) NOT NULL, revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_effects (
  message_sid VARCHAR(64) NOT NULL, kind VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL,
  result LONGBLOB, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (message_sid, kind)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_outbox (
  id CHAR(36) PRIMARY KEY, message_sid VARCHAR(64) NOT NULL, position INT NOT NULL, phone VARCHAR(32) NOT NULL,
  payload LONGBLOB NOT NULL, status VARCHAR(20) NOT NULL DEFAULT 'pending', remote_sid VARCHAR(64) UNIQUE,
  attempts INT NOT NULL DEFAULT 0, available_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  error_code VARCHAR(80), created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY output_once (message_sid, position), INDEX outbox_ready (status, available_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_delivery_events (
  event_hash CHAR(64) PRIMARY KEY, outbox_id CHAR(36), remote_sid VARCHAR(64) NOT NULL,
  status VARCHAR(30) NOT NULL, error_code VARCHAR(80), created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX delivery_message (remote_sid, created_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_admins (
  id INT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(100) NOT NULL, role VARCHAR(16) NOT NULL DEFAULT 'admin',
  active BOOLEAN NOT NULL DEFAULT TRUE, session_version INT NOT NULL DEFAULT 1,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_admin_sessions (
  sid VARCHAR(128) PRIMARY KEY, data LONGBLOB NOT NULL, expires_at DATETIME(3) NOT NULL,
  INDEX admin_session_expiry (expires_at)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_login_limits (
  bucket CHAR(64) PRIMARY KEY, attempts INT NOT NULL DEFAULT 0, window_start DATETIME(3) NOT NULL
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_alerts (
  alert_key VARCHAR(100) PRIMARY KEY, severity VARCHAR(20) NOT NULL, message VARCHAR(500) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE, first_seen DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  last_seen DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), resolved_at DATETIME(3),
  notified_at DATETIME(3), notification_error VARCHAR(150)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_runtime (
  name VARCHAR(60) PRIMARY KEY, data JSON NOT NULL, updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bot_audit (
  id BIGINT AUTO_INCREMENT PRIMARY KEY, admin_id INT, action VARCHAR(80) NOT NULL,
  target VARCHAR(100), created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
